fix: error message for missing config file

diff --git a/bg3overlay b/bg3overlay
--- a/bg3overlay
+++ b/bg3overlay
@@ -1,58 +1,59 @@
 #!/usr/bin/env bash
 die() {
-  echo "${1}"
-  exit 1
+	echo "${1}"
+	exit 1
 }
 
 mount_overlay() {
-  mv "${BG3_INSTALL_DIR}" bg3.base
-  mkdir "${BG3_INSTALL_DIR}"
-  mkdir -p /tmp/bg3/{upper,work}
+	mv "${BG3_INSTALL_DIR}" bg3.base
+	mkdir "${BG3_INSTALL_DIR}"
+	mkdir -p /tmp/bg3/{upper,work}
 
-  declare -A _modulars=()
+	declare -A _modulars=()
 
-  _current="$(dirname "${BG3_DATA_DIR}")/current"
-  if [ -d "${_current}/modular-override" ]; then
-    pushd "${_current}/modular-override"
-    for _override in *
-    do
-      [ -d "${_override}" ] && _modulars["${_override}"]="${_current}/modular-override/${_override}" \
-        && echo "Found modular loose files mod “${_override}” …"
-    done
-    popd
-  fi
+	_current="$(dirname "${BG3_DATA_DIR}")/current"
+	if [ -d "${_current}/modular-override" ]; then
+		pushd "${_current}/modular-override"
+		for _override in *; do
+			[ -d "${_override}" ] && _modulars["${_override}"]="${_current}/modular-override/${_override}" &&
+				echo "Found modular loose files mod “${_override}” …"
+		done
+		popd
+	fi
 
-  if [[ ! "${#_modulars[*]}" -eq 0 ]]; then
-    # fugly, but I give up on doing this properly for now
-    _modular_overrides=$(printf "%s♫" ${_modulars[@]// /\\ })
-    _modular_overrides=${_modular_overrides//\\♫/\\ }
-    _modular_overrides=${_modular_overrides//♫/:}
-  fi
+	if [[ ! "${#_modulars[*]}" -eq 0 ]]; then
+		# fugly, but I give up on doing this properly for now
+		_modular_overrides=$(printf "%s♫" ${_modulars[@]// /\\ })
+		_modular_overrides=${_modular_overrides//\\♫/\\ }
+		_modular_overrides=${_modular_overrides//♫/:}
+	fi
 
-  fuse-overlayfs -o lowerdir="${_current}/override":"${_modular_overrides}""$(dirname "${BG3_INSTALL_DIR}")/bg3.base",upperdir=/tmp/bg3/upper,workdir=/tmp/bg3/work overlayfs "${BG3_INSTALL_DIR}"
+	fuse-overlayfs -o lowerdir="${_current}/override":"${_modular_overrides}""$(dirname "${BG3_INSTALL_DIR}")/bg3.base",upperdir=/tmp/bg3/upper,workdir=/tmp/bg3/work overlayfs "${BG3_INSTALL_DIR}"
 }
 
 unmount_overlay() {
-  fusermount -u "${BG3_INSTALL_DIR}"
-  rmdir "${BG3_INSTALL_DIR}"
-  mv bg3.base "${BG3_INSTALL_DIR}"
-  rm -rf /tmp/bg3/work
+	fusermount -u "${BG3_INSTALL_DIR}"
+	rmdir "${BG3_INSTALL_DIR}"
+	mv bg3.base "${BG3_INSTALL_DIR}"
+	rm -rf /tmp/bg3/work
 }
 
 for _dep in fuse-overlayfs fusermount; do
-    command -v "${_dep}" > /dev/null || die "Command \"${_dep}\" not found. Please install it and try again."
+	command -v "${_dep}" >/dev/null || die "Command \"${_dep}\" not found. Please install it and try again."
 done
 
 source "$(dirname "$(realpath "$0")")/util/folders.sh"
 
 CONFIG_FILE="${CONFIG_FILE:-${XDG_CONFIG_HOME:-$HOME/.config}/bg3-mod-profiles/config}"
-while read line; do declare "$line"; done < "${CONFIG_FILE}"
+if [ -f "${CONFIG_FILE}"]; then
+	while read line; do declare "$line"; done <"${CONFIG_FILE}"
+fi
 
 if [ -z "${BG3_DATA_DIR}" ] || [ -z "${BG3_INSTALL_DIR}" ]; then
-  _library="$(getBg3Library)"
-  [ $? -eq 1 ] && echo "Steam library folder for Baldur’s Gate 3 not found! Exiting …" && exit 1
-  BG3_DATA_DIR="${_library}/steamapps/compatdata/1086940/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3"
-  BG3_INSTALL_DIR="${_library}/steamapps/common/Baldurs Gate 3"
+	_library="$(getBg3Library)"
+	[ $? -eq 1 ] && echo "Steam library folder for Baldur’s Gate 3 not found! Exiting …" && exit 1
+	BG3_DATA_DIR="${_library}/steamapps/compatdata/1086940/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3"
+	BG3_INSTALL_DIR="${_library}/steamapps/common/Baldurs Gate 3"
 fi
 
 cd "$(dirname "${BG3_INSTALL_DIR}")"
@@ -61,35 +62,35 @@ mount | grep "${BG3_INSTALL_DIR}" >/dev/null 2>&1
 _mounted=$?
 
 case $1 in
-  --disable)
-    if [ ${_mounted} -eq 1 ]; then
-      echo "Overlay not mounted."
-      exit 1
-    fi
-    unmount_overlay
-    [ -f "$(dirname "${CONFIG_FILE}")/bg3overlay.post" ] && . "$(dirname "${CONFIG_FILE}")/bg3overlay.post"
-    [ -f "$(dirname "$(realpath "$0")")/bg3overlay.post" ] && . "$(dirname "$(realpath "$0")")/bg3overlay.post" \
-      && echo "Overlay hooks in the installation folder are deprecated. Please move them to $(dirname "${CONFIG_FILE}")/."
-    exit 0
-    ;;
-  --enable)
-    if [ ${_mounted} -eq 0 ]; then
-      echo "Overlay already mounted."
-      exit 1
-    fi
-    [ -f "$(dirname ${CONFIG_FILE})/bg3overlay.pre" ] && . "$(dirname ${CONFIG_FILE})/bg3overlay.pre"
-    [ -f "$(dirname $(realpath "$0"))/bg3overlay.pre" ] && . "$(dirname $(realpath "$0"))/bg3overlay.pre" \
-      && echo "Overlay hooks in the installation folder are deprecated. Please move them to $(dirname "${CONFIG_FILE}")/."
-    mount_overlay
-    exit 0
-    ;;
-  *)
-    cat << EOF
+--disable)
+	if [ ${_mounted} -eq 1 ]; then
+		echo "Overlay not mounted."
+		exit 1
+	fi
+	unmount_overlay
+	[ -f "$(dirname "${CONFIG_FILE}")/bg3overlay.post" ] && . "$(dirname "${CONFIG_FILE}")/bg3overlay.post"
+	[ -f "$(dirname "$(realpath "$0")")/bg3overlay.post" ] && . "$(dirname "$(realpath "$0")")/bg3overlay.post" &&
+		echo "Overlay hooks in the installation folder are deprecated. Please move them to $(dirname "${CONFIG_FILE}")/."
+	exit 0
+	;;
+--enable)
+	if [ ${_mounted} -eq 0 ]; then
+		echo "Overlay already mounted."
+		exit 1
+	fi
+	[ -f "$(dirname ${CONFIG_FILE})/bg3overlay.pre" ] && . "$(dirname ${CONFIG_FILE})/bg3overlay.pre"
+	[ -f "$(dirname $(realpath "$0"))/bg3overlay.pre" ] && . "$(dirname $(realpath "$0"))/bg3overlay.pre" &&
+		echo "Overlay hooks in the installation folder are deprecated. Please move them to $(dirname "${CONFIG_FILE}")/."
+	mount_overlay
+	exit 0
+	;;
+*)
+	cat <<EOF
 Usage: $(basename "$0") OPTION
 Options:
   --enable                      Mount overlayfs for current mod profile.
   --disable                     Unmount overlayfs.
 EOF
-    exit 1
-    ;;
+	exit 1
+	;;
 esac
diff --git a/bg3switch b/bg3switch
--- a/bg3switch
+++ b/bg3switch
@@ -1,105 +1,105 @@
 #!/usr/bin/env bash
-create () {
-  if [ -d "profiles/${1}" ]; then
-    echo "Baldur’s Gate 3 folder for \"${1}\" already exists."
-    exit 1
-  else
-    mkdir "profiles/${1}"
+create() {
+	if [ -d "profiles/${1}" ]; then
+		echo "Baldur’s Gate 3 folder for \"${1}\" already exists."
+		exit 1
+	else
+		mkdir "profiles/${1}"
 
-    switch "${1}"
-  fi
+		switch "${1}"
+	fi
 }
 
-link () {
-  if [ -z ${1} ]; then
-    _dir="current"
-  else
-    _dir="profiles/${1}"
-  fi
+link() {
+	if [ -z ${1} ]; then
+		_dir="current"
+	else
+		_dir="profiles/${1}"
+	fi
 
-  # sym link the “Mods” folder
-  if [ ! -L "Baldur's Gate 3/Mods" ]; then
-    echo "Non-link \"Mods\" folder detected! Setting up symbolic link …"
-    if [ -d "Baldur's Gate 3/Mods/" ]; then
-      mv "Baldur's Gate 3/Mods/" "${_dir}"
-    fi
-    ln -s "../current/Mods" "Baldur's Gate 3/Mods"
-  fi
-  if [ ! -d "${_dir}/Mods" ]; then
-    echo "Creating \"Mods\" folder …"
-    mkdir -p "${_dir}/Mods"
-  fi
+	# sym link the “Mods” folder
+	if [ ! -L "Baldur's Gate 3/Mods" ]; then
+		echo "Non-link \"Mods\" folder detected! Setting up symbolic link …"
+		if [ -d "Baldur's Gate 3/Mods/" ]; then
+			mv "Baldur's Gate 3/Mods/" "${_dir}"
+		fi
+		ln -s "../current/Mods" "Baldur's Gate 3/Mods"
+	fi
+	if [ ! -d "${_dir}/Mods" ]; then
+		echo "Creating \"Mods\" folder …"
+		mkdir -p "${_dir}/Mods"
+	fi
 
-  # sym link the modsettings file
-  mkdir -p "${_dir}/PlayerProfiles/Public/"
-  if [ ! -L "Baldur's Gate 3/PlayerProfiles/Public/modsettings.lsx" ]; then
-    echo "Non-link \"modsettings.lsx\" detected! Setting up symbolic link …"
-    if [ -f "${_dir}/PlayerProfiles/Public/modsettings.lsx" ]; then
-      mv "Baldur's Gate 3/PlayerProfiles/Public/modsettings.lsx" "${_dir}/PlayerProfiles/Public/"
-    fi
-    ln -s "../../../current/PlayerProfiles/Public/modsettings.lsx" "Baldur's Gate 3/PlayerProfiles/Public/"
-  fi
-  if [ ! -f "${_dir}/PlayerProfiles/Public/modsettings.lsx" ]; then
-    echo "Creating empty modsettings file …"
-    touch "${_dir}/PlayerProfiles/Public/modsettings.lsx"
-  fi
+	# sym link the modsettings file
+	mkdir -p "${_dir}/PlayerProfiles/Public/"
+	if [ ! -L "Baldur's Gate 3/PlayerProfiles/Public/modsettings.lsx" ]; then
+		echo "Non-link \"modsettings.lsx\" detected! Setting up symbolic link …"
+		if [ -f "${_dir}/PlayerProfiles/Public/modsettings.lsx" ]; then
+			mv "Baldur's Gate 3/PlayerProfiles/Public/modsettings.lsx" "${_dir}/PlayerProfiles/Public/"
+		fi
+		ln -s "../../../current/PlayerProfiles/Public/modsettings.lsx" "Baldur's Gate 3/PlayerProfiles/Public/"
+	fi
+	if [ ! -f "${_dir}/PlayerProfiles/Public/modsettings.lsx" ]; then
+		echo "Creating empty modsettings file …"
+		touch "${_dir}/PlayerProfiles/Public/modsettings.lsx"
+	fi
 
-  # sym link the “ScriptExtender” folder
-  if [ ! -L "Baldur's Gate 3/Script Extender" ]; then
-    echo "Non-link \"Script Extender\" folder detected! Setting up symbolic link …"
-    if [ -d "Baldur's Gate 3/Script Extender/" ]; then
-      mv "Baldur's Gate 3/Script Extender/" "${_dir}"
-    fi
-    ln -s "../current/Script Extender" "Baldur's Gate 3/Script Extender"
-  fi
-  if [ ! -d "${_dir}/Script Extender" ]; then
-    echo "Creating \"Script Extender\" folder …"
-    mkdir -p "${_dir}/Script Extender"
-  fi
+	# sym link the “ScriptExtender” folder
+	if [ ! -L "Baldur's Gate 3/Script Extender" ]; then
+		echo "Non-link \"Script Extender\" folder detected! Setting up symbolic link …"
+		if [ -d "Baldur's Gate 3/Script Extender/" ]; then
+			mv "Baldur's Gate 3/Script Extender/" "${_dir}"
+		fi
+		ln -s "../current/Script Extender" "Baldur's Gate 3/Script Extender"
+	fi
+	if [ ! -d "${_dir}/Script Extender" ]; then
+		echo "Creating \"Script Extender\" folder …"
+		mkdir -p "${_dir}/Script Extender"
+	fi
 
-  # create override folders for loose files mods
-  if [ ! -d "${_dir}/override" ]; then
-    echo "Creating \"override\" folder …"
-    mkdir "${_dir}/override"
-  fi
-  if [ ! -d "${_dir}/modular-override" ]; then
-    echo "Creating \"modular-override\" folder …"
-    mkdir "${_dir}/modular-override"
-  fi
+	# create override folders for loose files mods
+	if [ ! -d "${_dir}/override" ]; then
+		echo "Creating \"override\" folder …"
+		mkdir "${_dir}/override"
+	fi
+	if [ ! -d "${_dir}/modular-override" ]; then
+		echo "Creating \"modular-override\" folder …"
+		mkdir "${_dir}/modular-override"
+	fi
 }
 
-list () {
-  if [ -d "profiles" ]; then
-    echo -e "Mod Profiles:"
-    ls profiles | tr " " "\n"
-  else
-    echo "No profile folder present. Try \"$(basename $0) --create PROFILE\"."
-  fi
-  current=$(readlink -- current)
-  if [ -z $current ]; then
-    echo -e "\nNo link to current profile found. Try \"$(basename $0) --create PROFILE\"."
-  else
-    echo -e "\nCurrent Profile:\n${current##*/}"
-  fi
+list() {
+	if [ -d "profiles" ]; then
+		echo -e "Mod Profiles:"
+		ls profiles | tr " " "\n"
+	else
+		echo "No profile folder present. Try \"$(basename $0) --create PROFILE\"."
+	fi
+	current=$(readlink -- current)
+	if [ -z $current ]; then
+		echo -e "\nNo link to current profile found. Try \"$(basename $0) --create PROFILE\"."
+	else
+		echo -e "\nCurrent Profile:\n${current##*/}"
+	fi
 }
 
-switch () {
-  if [ -z "${1}" ]; then
-    echo "No profile name given!"
-    exit 1
-  fi
+switch() {
+	if [ -z "${1}" ]; then
+		echo "No profile name given!"
+		exit 1
+	fi
 
-  if [ -d "profiles/${1}" ]; then
-    link "${1}"
-    ln -nsf "./profiles/${1}" current
-  else
-    echo "No Baldur’s Gate 3 folder for \"${1}\" found. Try \"$(basename $0) --help\""
-    exit 1
-  fi
+	if [ -d "profiles/${1}" ]; then
+		link "${1}"
+		ln -nsf "./profiles/${1}" current
+	else
+		echo "No Baldur’s Gate 3 folder for \"${1}\" found. Try \"$(basename $0) --help\""
+		exit 1
+	fi
 }
 
-usage () {
-  cat << EOF
+usage() {
+	cat <<EOF
 Usage: $(basename $0) [OPTION] PROFILE
 Options:
   --create,--add,--new          Creates a new mod profile under PROFILE. If this is your first,
@@ -118,40 +118,43 @@ EOF
 
 source "$(dirname $(realpath $0))/util/folders.sh"
 
-while read line; do declare "$line"; done < "${CONFIG_FILE:-${XDG_CONFIG_HOME:-$HOME/.config}/bg3-mod-profiles/config}"
+CONFIG_FILE="${CONFIG_FILE:-${XDG_CONFIG_HOME:-$HOME/.config}/bg3-mod-profiles/config}"
+if [ -f "${CONFIG_FILE}"]; then
+	while read line; do declare "$line"; done <"${CONFIG_FILE}"
+fi
 
 if [ -z "$BG3_DATA_DIR" ]; then
-  _library="$(getBg3Library)"
-  [ $? -eq 1 ] && echo "Steam library folder for Baldur’s Gate 3 not found! Exiting …" && exit 1
-  BG3_DATA_DIR="${_library}/steamapps/compatdata/1086940/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3/"
+	_library="$(getBg3Library)"
+	[ $? -eq 1 ] && echo "Steam library folder for Baldur’s Gate 3 not found! Exiting …" && exit 1
+	BG3_DATA_DIR="${_library}/steamapps/compatdata/1086940/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3/"
 fi
 
 cd "$(dirname "${BG3_DATA_DIR}")"
 
 case "$1" in
-  --create|--add|--new)
-    create "$2"
-    ;;
-  --help|-h)
-    usage
-    exit 1
-    ;;
-  --link)
-    link "$2"
-    ;;
-  --list|--ls)
-    list
-    ;;
-  --open|--cd)
-    $SHELL
-    ;;
-  --switch)
-    switch "$2"
-    ;;
-  "")
-    list
-    ;;
-  *)
-    switch "$1"
-    ;;
+--create | --add | --new)
+	create "$2"
+	;;
+--help | -h)
+	usage
+	exit 1
+	;;
+--link)
+	link "$2"
+	;;
+--list | --ls)
+	list
+	;;
+--open | --cd)
+	$SHELL
+	;;
+--switch)
+	switch "$2"
+	;;
+"")
+	list
+	;;
+*)
+	switch "$1"
+	;;
 esac
